#!/usr/bin/env ruby
# frozen_string_literals: true
#/ Usage: script/import-overcast-podcast-favorites
#/ Imports favorited/recommended episodes to _data.

require 'base64'
require 'bundler/setup'
require 'json'
require 'tempfile'
require_relative 'lib/podcast_overrides'
require_relative 'lib/podcast_episode_overrides'
require_relative 'lib/podcast_episode_backfill'

OVERCAST_FM_PERMALINK_BASE = "https://overcast.fm/+"

opts = {
  oc_db_path: ARGV.first,
  data_file_path: File.expand_path("../_data/overcast_recommended_episodes.json", __dir__),
  sql_query_file: File.expand_path("import_overcast_podcast_favorites.sql", __dir__),
}

if opts[:oc_db_path].nil? || opts[:oc_db_path].empty?
  abort "fatal: overcast container db.sqlite path argument required"
end

puts `sqlite-utils query "#{opts[:oc_db_path]}" "$(<#{opts[:sql_query_file]})" > "#{opts[:data_file_path]}"`
unless $?.success?
  abort "fatal: sqlite-utils failed"
end

def overcast_fm_permalink(episodeIDDecimal)
  # Marco kindly shared the algorithm for generating the overcast.fm permalinks for episodes:
  # https://mastodon.social/@overcastfm/109863328508642286
  # Each episode ID is a 64-bit integer containing both the feed ID (upper 32 bits) and episode ID (lower 32 bits)
  # It's then base64 encoded, removing leading A's and trailing ='s.
  uri = Base64.urlsafe_encode64([episodeIDDecimal >> 32, episodeIDDecimal & 0xFFFFFFFF].pack('N2'))
  uri.sub!(%r{\AA*}, '') # trim leading A's
  uri.sub!(%r{=*\z}, '') # trim trailing ='s
  uri.tr!('+/', '-_') # replace +'s and /'s with - and _
  OVERCAST_FM_PERMALINK_BASE + uri
end

def ensure_https(link)
  if link.start_with?("https://")
    link
  else
    link.sub("http://", "https://")
  end
end

def process_episode_for_overrides(episode)
  if PODCAST_OVERRIDES.key?(episode["podcastID"])
    episode.merge!(PODCAST_OVERRIDES[episode["podcastID"]])
  end
  if PODCAST_EPISODE_OVERRIDES.key?(episode["episodeID"])
    episode.merge!(PODCAST_EPISODE_OVERRIDES[episode["episodeID"]])
  end
end

episodes = JSON.parse(File.read(opts[:data_file_path]))
episodes.each do |episode|
  episode["overcastFMPermalink"] = overcast_fm_permalink(episode.fetch("episodeID"))
  episode["podcastURL"] = ensure_https(episode["podcastURL"]) if episode["podcastURL"]
  episode["episodeURL"] = ensure_https(episode["episodeURL"]) if episode["episodeURL"]
  episode["podcastArtworkURL"] = ensure_https(episode["podcastArtworkURL"]) if episode["podcastArtworkURL"]
  process_episode_for_overrides(episode)
end

episodes.concat(PODCAST_EPISODE_BACKFILL)
episodes.sort_by! { |episode| episode["userRecommendedTime"] }.reverse!

File.write(opts[:data_file_path], JSON.pretty_generate(episodes))
