#!/usr/bin/env ruby
# frozen_string_literals: true
#/ Usage: script/import-overcast-podcast-favorites
#/ Imports favorited/recommended episodes to _data.

require 'base64'
require 'bundler/setup'
require 'json'
require 'tempfile'

OVERCAST_FM_PERMALINK_BASE = "https://overcast.fm/+"

opts = {
  oc_db_path: ARGV.first,
  data_file_path: File.expand_path("../_data/overcast_listened_episodes.json", __dir__),
  sql_query_file: File.expand_path("import_overcast_podcast_listened.sql", __dir__),
}

if opts[:oc_db_path].nil? || opts[:oc_db_path].empty?
  abort "fatal: overcast container db.sqlite path argument required"
end

puts `sqlite-utils "#{opts[:oc_db_path]}" "$(<#{opts[:sql_query_file]})" > "#{opts[:data_file_path]}"`
unless $?.success?
  abort "fatal: sqlite-utils failed"
end

def overcast_fm_permalink(episodeIDDecimal)
  # Marco kindly shared the algorithm for generating the overcast.fm permalinks for episodes:
  # https://mastodon.social/@overcastfm/109863328508642286
  # Each episode ID is a 64-bit integer containing both the feed ID (upper 32 bits) and episode ID (lower 32 bits)
  # It's then base64 encoded, removing leading A's and trailing ='s.
  uri = Base64.urlsafe_encode64([episodeIDDecimal >> 32, episodeIDDecimal & 0xFFFFFFFF].pack('N2'))
  uri.sub!(%r{\AA*}, '') # trim leading A's
  uri.sub!(%r{=*\z}, '') # trim trailing ='s
  uri.tr!('+/', '-_') # replace +'s and /'s with - and _
  OVERCAST_FM_PERMALINK_BASE + uri
end

episodes = JSON.parse(File.read(opts[:data_file_path]))
episodes.each do |episode|
  episode["overcastFMPermalink"] = overcast_fm_permalink(episode.fetch("episodeID"))
end

File.write(opts[:data_file_path], JSON.pretty_generate(episodes))
