#!/usr/bin/env ruby

trap("SIGINT") { exit! }

require 'rubygems'
require 'yaml'
require 'net/http'
require 'openssl'
require 'html-proofer'

verbose = !!ENV["VERBOSE"]

URL_IGNORE = [
  /faz\.net/,
  /github\.com/,
  /www\.shirky\.com/, # :(
  /staff\.washington\.edu/,
  /ping\.parkermoo\.re/,
  /vimeo\.com/,
]

HTMLProofer.check_directory("./_site", {
  checks_to_ignore: ["ScriptCheck"],
  url_ignore: URL_IGNORE,
  ignore_urls: URL_IGNORE,
  file_ignore: [%r{\./_site/mirrors/}],
  ignore_files: [%r{\./_site/mirrors/}],
  only_4xx: true,
  enforce_https: true,
  verbose: verbose,
  typhoeus: { timeout: 5, connecttimeout: 5, verbose: verbose },
  parallel: { in_processes: 10 }
}).run
