#!/usr/bin/env ruby

trap("SIGINT") { exit! }

require 'rubygems'
require 'yaml'
require 'net/http'
require 'openssl'
require 'html/proofer'

class HTML::Proofer
  def get_checks
    %w{Images Links}
  end

  def files
    Dir.glob("#{@src}/**/*#{@options[:ext]}").reject { |f| f.start_with?(File.join(@src, "mirrors")) }
  end
end

proofer = HTML::Proofer.new("./_site", {
  href_ignore: [/faz\.net/, /github\.com/, /staff.washington.edu/],
  typhoeus: { timeout: 5, connecttimeout: 5 },
  verbose: !!ENV['VERBOSE']
}).run
