name: Replace old links with archived links
on:
  schedule:
    - cron: "14 4 * * *"
  workflow_dispatch:
  push:
    branches: [linkrot.yml]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fix links
        uses: parkr/notfoundbot@2aa183ab653118a1610c6ff2095375c785bae100
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
