name: Replace old links with archived links
on:
  schedule:
    - cron: "14 4 * * *"
  workflow_dispatch:
  push:
    paths:
    - .github/workflows/linkrot.yml

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fix links
        uses: parkr/notfoundbot@patch-1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
