name: Replace old links with archived links
on:
  schedule:
    - cron: "14 4 * * *"
  workflow_dispatch:
  push:
    branches: [linkrot.yml]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fix links
        uses: parkr/notfoundbot@ed78a3d0fe1df0130800db288bdd0bf5341d5f18
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
