name: Replace old links with archived links
on:
  schedule:
    - cron: "14 4 * * *"
  workflow_dispatch:
  push:
    branches: [linkrot.yml]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fix links
        uses: parkr/notfoundbot@a8716030b02b9110e73b5a3a939a110ce726546b
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
