name: Replace old links with archived links
on:
  schedule:
    - cron: "14 4 * * *"
  workflow_dispatch:
  push:
    branches: [linkrot.yml]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fix links
        # TODO(parkr): update once https://github.com/tmcw/notfoundbot/pull/65 is merged
        uses: parkr/notfoundbot@patch-1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
